# Generated by Django 2.2.6 on 2019-11-01 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('email_extras', '0004_use_djangos_emailfield'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='address',
            unique_together={('address', 'key')},
        ),
    ]
